### ISSUE TITLE
初次翻译一些疑问

### ISSUE THREAD

**Issue by mapleray** [veficos/reverse-engineering-for-beginners#1]
1. 修缮翻译对照的是原书最新版 http://beginners.re/Reverse_Engineering_for_Beginners-en.pdf 还是该书对应的项目仓库？
2. 翻译时是否需要标注下章节进度？怕几人同时翻译同一章节
3. 翻译的需要注意的格式要求？

**Comment by veficos** [comment]
你好。

1. 主要的是针对原书最新版 http://beginners.re/Reverse_Engineering_for_Beginners-en.pdf 进行修缮和维护，作者的项目仓库更新太快，而且没release可能会有些Bug。另外我们也没有精力和作者保持同步更新。
2. 我的想法是每个工作都在分支上开一个issue，然后由一个人或者一个小组进行跟近和进度报告。如果你有更好的维护建议欢迎提出。
3. 格式需要统一，具体还没定好，到时候开个issue然后我拉大家到群里讨论一下。

目前有小伙伴在做目录的分类和列出与原版的diff，好进行下一步工作。

**Comment by mapleray** [comment]
感谢

**Comment by veficos** [comment]
欢迎加入。
