### ISSUE TITLE
第二章中 部分翻译 感觉不太正确

### ISSUE THREAD

**Issue by xqin** [veficos/reverse-engineering-for-beginners#2]
https://github.com/veficos/reverse-engineering-for-beginners/blob/master/Chapter-02/Chapter-2.md

在介绍 gcc x86 的时候,有一段话(如下图),  `这条指令该指令,  在16字节边界在, 这导致堆栈对准的所有值` 这几句读起来总感觉怪怪的.

![image](https://cloud.githubusercontent.com/assets/1265888/15598553/d8e8c9d8-240d-11e6-936b-b25ac76a8150.png)

原文中的内容如下:  (this instruction aligns the ESP register value on a 16-byte boundary, This results in all values in the stack being aligned the same way)

![image](https://cloud.githubusercontent.com/assets/1265888/15598565/e2a0bbde-240d-11e6-883e-198d0ef58d0a.png)

下面是Google的翻译(仅供参考):

![image](https://cloud.githubusercontent.com/assets/1265888/15598573/ed7ad472-240d-11e6-8137-5ea4b2ccbfa3.png)

![image](https://cloud.githubusercontent.com/assets/1265888/15598575/ef531930-240d-11e6-808b-293310a331be.png)

具体怎么翻译, 我英文不好, 也不太确定, 但目前的翻译, 感觉上肯定是有点问题的.

最后, 非常感谢您们的无私付出.

**Comment by veficos** [comment]
谢谢指出，我会尽快修复

**Comment by veficos** [comment]
你好，我已经简单修复了第二章你所指出的问题。如果你还是觉得不妥，可以fork这个分支后做修缮，然后再push给我来统一你的贡献。我希望你也能加入到这项工作当中。如果觉得这项工作挺有趣的话可以加我的QQ。

另外我私自把你作为贡献者放到贡献名单上，如果你觉得不妥的话可以跟我反馈一下。
